package it.baldilorenzo.hibernate_envers_101.demo;

import it.baldilorenzo.hibernate_envers_101.audit.AuditUserContext;
import it.baldilorenzo.hibernate_envers_101.domain.Address;
import it.baldilorenzo.hibernate_envers_101.domain.Category;
import it.baldilorenzo.hibernate_envers_101.domain.Customer;
import it.baldilorenzo.hibernate_envers_101.domain.Product;
import it.baldilorenzo.hibernate_envers_101.dto.RevisionDto;
import it.baldilorenzo.hibernate_envers_101.repository.CategoryRepository;
import it.baldilorenzo.hibernate_envers_101.service.CustomerService;
import it.baldilorenzo.hibernate_envers_101.service.ProductService;
import jakarta.persistence.EntityManager;
import jakarta.persistence.PersistenceContext;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.ApplicationArguments;
import org.springframework.boot.ApplicationRunner;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.stereotype.Component;
import org.springframework.transaction.PlatformTransactionManager;
import org.springframework.transaction.TransactionDefinition;
import org.springframework.transaction.support.TransactionTemplate;

import java.math.BigDecimal;
import java.time.Instant;
import java.util.List;
import java.util.Map;
import java.util.function.Supplier;

/**
 * On application startup runs a sequence of scenarios that exercise every
 * Envers feature shown in this project:
 *
 *  1. CREATE / UPDATE / add relationships / DELETE -> ADD/MOD/DEL revisions
 *  2. Reading the full history
 *  3. Snapshot of the entity at a specific revision
 *  4. Snapshot at a given timestamp
 *  5. Diff between two revisions
 *  6. Application-level rollback
 *  7. Selective auditing (@NotAudited) on products
 *  8. Envers query with criteria on a field value (price)
 *  9. Snapshot by category at a specific revision
 *
 * Every "write operation" runs in a separate transaction with a different
 * username, so in the REVINFO table you can see different users as authors
 * of the changes.
 */
@Component
@ConditionalOnProperty(name = "demo.enabled", havingValue = "true", matchIfMissing = true)
public class DemoRunner implements ApplicationRunner {

    private static final Logger log = LoggerFactory.getLogger(DemoRunner.class);
    private static final String LINE = "=".repeat(70);

    private final CustomerService customerService;
    private final ProductService productService;
    private final CategoryRepository categoryRepository;
    private final TransactionTemplate tx;

    @PersistenceContext
    private EntityManager entityManager;

    @Value("${demo.reset:true}")
    private boolean reset;

    public DemoRunner(CustomerService customerService,
                      ProductService productService,
                      CategoryRepository categoryRepository,
                      PlatformTransactionManager txManager) {
        this.customerService = customerService;
        this.productService = productService;
        this.categoryRepository = categoryRepository;
        // every step is a separate transaction = a separate revision
        this.tx = new TransactionTemplate(txManager);
        this.tx.setPropagationBehavior(TransactionDefinition.PROPAGATION_REQUIRES_NEW);
    }

    @Override
    public void run(ApplicationArguments args) {
        log.info("\n{}\n  HIBERNATE ENVERS DEMO\n{}", LINE, LINE);

        if (reset) {
            resetSchema();
        }

        scenarioCustomer();
        scenarioProduct();

        log.info("\n{}\n  DEMO COMPLETED - application listening on :8080\n{}", LINE, LINE);
    }

    // --------------------------------------------------------------- reset

    /**
     * Wipes data and _AUD tables to make the demo reproducible.
     *
     * 1. TRUNCATE ... RESTART IDENTITY CASCADE clears the rows AND the
     *    IDENTITY-owned sequences (e.g. customer.id, product.id).
     * 2. The REVINFO id is generated by an independent Postgres sequence
     *    (Hibernate maps DefaultRevisionEntity#id to @GeneratedValue=AUTO
     *    which becomes a SEQUENCE on Postgres). RESTART IDENTITY does NOT
     *    touch independent sequences, so without the second step the
     *    revision numbers would keep growing across restarts and a query
     *    like getAtRevision(customerId, 1) would fail with
     *    "No version of Customer 1 at revision 1" on every run after the first.
     */
    private void resetSchema() {
        tx.executeWithoutResult(s -> {
            entityManager.createNativeQuery("""
                    TRUNCATE TABLE
                        address_aud, customer_aud, product_aud,
                        address, customer, product, category, revinfo
                    RESTART IDENTITY CASCADE
                    """).executeUpdate();

            // Reset every standalone sequence (including revinfo_seq /
            // hibernate_sequence) so revision numbers also restart from 1.
            entityManager.createNativeQuery("""
                    DO $$
                    DECLARE seq_name text;
                    BEGIN
                        FOR seq_name IN
                            SELECT c.relname FROM pg_class c WHERE c.relkind = 'S'
                        LOOP
                            EXECUTE format('ALTER SEQUENCE %I RESTART WITH 1', seq_name);
                        END LOOP;
                    END $$;
                    """).executeUpdate();
        });
        log.info(">> schema cleared (tables + all sequences)");
    }

    // ----------------------------------------------------------- customer

    private void scenarioCustomer() {
        log.info("\n--- SCENARIO 1: Customer (full audit + relationships) ---");

        // STEP 1 - create as alice
        Long customerId = asUser("alice", () -> tx.execute(s -> {
            Customer c = new Customer("Mario", "Rossi", "mario.rossi@example.com");
            return customerService.create(c).getId();
        }));
        log.info("[alice] CREATED customer id={}", customerId);

        // STEP 2 - add address as alice
        asUser("alice", () -> tx.executeWithoutResult(s -> {
            customerService.addAddress(customerId,
                    new Address("Via Roma 1", "Milano", "20100"));
        }));
        log.info("[alice] ADDED address");

        // STEP 3 - update lastname as bob
        asUser("bob", () -> tx.executeWithoutResult(s -> {
            Customer payload = new Customer("Mario", "Bianchi", "mario.rossi@example.com");
            customerService.update(customerId, payload);
        }));
        log.info("[bob]   UPDATED lastname Rossi -> Bianchi");

        // STEP 4 - update email as carol
        Instant beforeFinalEdit = Instant.now();
        sleep(50);
        asUser("carol", () -> tx.executeWithoutResult(s -> {
            Customer current = customerService.findById(customerId);
            Customer payload = new Customer(current.getFirstName(), current.getLastName(),
                    "mario.bianchi@example.com");
            customerService.update(customerId, payload);
        }));
        log.info("[carol] UPDATED email");

        // -------- reads --------

        log.info("\n>> Full history:");
        List<RevisionDto<Customer>> history = txRead(() -> customerService.getHistory(customerId));
        history.forEach(r -> log.info("   rev={} {} by {} -> {} {} <{}>",
                r.revisionNumber(), r.revisionType(), r.username(),
                r.entity().getFirstName(), r.entity().getLastName(), r.entity().getEmail()));

        log.info("\n>> Revision numbers: {}",
                txRead(() -> customerService.getRevisionNumbers(customerId)));

        log.info("\n>> State at rev 1 (initial snapshot):");
        Customer rev1 = txRead(() -> customerService.getAtRevision(customerId, 1));
        log.info("   {} {} <{}>", rev1.getFirstName(), rev1.getLastName(), rev1.getEmail());

        log.info("\n>> State at instant {} (just before the last update):",
                beforeFinalEdit);
        Customer atDate = txRead(() -> customerService.getAtDate(customerId, beforeFinalEdit));
        log.info("   {} {} <{}>", atDate.getFirstName(), atDate.getLastName(), atDate.getEmail());

        log.info("\n>> Diff between rev 1 and rev 4:");
        Map<String, Object[]> diff = txRead(() -> customerService.diff(customerId, 1, 4));
        diff.forEach((field, ba) ->
                log.info("   {}: '{}' -> '{}'", field, ba[0], ba[1]));

        log.info("\n>> Rollback to rev 1 as admin:");
        asUser("admin", () -> tx.executeWithoutResult(s -> customerService.revertTo(customerId, 1)));
        Customer afterRevert = txRead(() -> customerService.findById(customerId));
        log.info("   current state: {} {} <{}>",
                afterRevert.getFirstName(), afterRevert.getLastName(), afterRevert.getEmail());
        log.info("   updated history (note the final rollback rev):");
        txRead(() -> customerService.getHistory(customerId)).forEach(r ->
                log.info("   rev={} {} by {} -> {} {}",
                        r.revisionNumber(), r.revisionType(), r.username(),
                        r.entity().getFirstName(), r.entity().getLastName()));

        log.info("\n>> Deletion (DEL revision):");
        asUser("admin", () -> tx.executeWithoutResult(s -> customerService.delete(customerId)));
        log.info("   final history:");
        txRead(() -> customerService.getHistory(customerId)).forEach(r ->
                log.info("   rev={} {} by {}", r.revisionNumber(), r.revisionType(), r.username()));
    }

    // ----------------------------------------------------------- product

    private void scenarioProduct() {
        log.info("\n--- SCENARIO 2: Product (selective auditing) ---");

        Long electronicsId = asUser("alice", () -> tx.execute(s -> {
            Category c = categoryRepository.save(new Category("Electronics"));
            return c.getId();
        }));
        Long booksId = asUser("alice", () -> tx.execute(s -> {
            Category c = categoryRepository.save(new Category("Books"));
            return c.getId();
        }));

        // Create two products
        Long laptopId = asUser("alice", () -> tx.execute(s -> {
            Product p = new Product("LP-001", "Laptop", new BigDecimal("1000.00"), 10);
            return productService.create(p, electronicsId).getId();
        }));
        Long bookId = asUser("alice", () -> tx.execute(s -> {
            Product p = new Product("BK-001", "Effective Java", new BigDecimal("45.00"), 50);
            return productService.create(p, booksId).getId();
        }));
        log.info("[alice] CREATED products laptop={} book={}", laptopId, bookId);

        // Price change (creates a revision)
        asUser("bob", () -> tx.executeWithoutResult(s ->
                productService.updatePrice(laptopId, new BigDecimal("1200.00"))));
        log.info("[bob]   PRICE laptop 1000 -> 1200 (creates a revision)");

        // Stock change (does NOT create a revision: @NotAudited)
        asUser("bob", () -> tx.executeWithoutResult(s ->
                productService.updateStock(laptopId, 5)));
        log.info("[bob]   STOCK laptop 10 -> 5 (does NOT create a revision because @NotAudited)");

        // Another price change
        asUser("carol", () -> tx.executeWithoutResult(s ->
                productService.updatePrice(laptopId, new BigDecimal("1500.00"))));
        log.info("[carol] PRICE laptop 1200 -> 1500");

        // -------- reads --------

        log.info("\n>> Laptop history (note: the stock change is missing):");
        List<RevisionDto<Product>> priceChanges = txRead(() ->
                productService.findPriceChangesAbove(laptopId, BigDecimal.ZERO));
        priceChanges.forEach(r -> log.info("   rev={} {} by {} -> price={}",
                r.revisionNumber(), r.revisionType(), r.username(), r.entity().getPrice()));

        log.info("\n>> Only prices above 1300 (AuditEntity.property criterion):");
        txRead(() -> productService.findPriceChangesAbove(laptopId, new BigDecimal("1300")))
                .forEach(r -> log.info("   rev={} price={}", r.revisionNumber(), r.entity().getPrice()));

        log.info("\n>> Snapshot of Electronics products at the latest product revision:");
        // last revision number for the laptop
        Number lastRev = (Number) entityManager.createNativeQuery(
                "select max(rev) from product_aud where id = :id")
                .setParameter("id", laptopId).getSingleResult();
        txRead(() -> productService.snapshotByCategory(lastRev, "Electronics"))
                .forEach(p -> log.info("   {} - {} ({} EUR)", p.getCode(), p.getName(), p.getPrice()));
    }

    // ----------------------------------------------------- helpers

    private void asUser(String user, Runnable action) {
        try {
            AuditUserContext.setUser(user);
            action.run();
        } finally {
            AuditUserContext.clear();
        }
    }

    private <T> T asUser(String user, Supplier<T> action) {
        try {
            AuditUserContext.setUser(user);
            return action.get();
        } finally {
            AuditUserContext.clear();
        }
    }

    private <T> T txRead(Supplier<T> action) {
        return tx.execute(s -> action.get());
    }

    private static void sleep(long ms) {
        try { Thread.sleep(ms); } catch (InterruptedException e) { Thread.currentThread().interrupt(); }
    }
}
